project2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('teamlead.urls', namespace='teamlead')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

teamlead/urls.py
from django.urls import path

from . import views

app_name = 'teamlead'

urlpatterns = [
    path('', views.index, name='index'),
    path('demand/', views.demand, name='demand'),
    path('geography/', views.geography, name='geography'),
    path('latest_vacancies/', views.latest_vacancies, name='latest_vacancies'),
    path('skills/', views.skills, name='skills'),
    
]

teamlead/models.py
from django.db import models

class indexPage(models.Model):
    name = models.TextField('Заголовок')
    text1 = models.TextField("Первый абзац")
    image1 = models.ImageField(
        'Картинка 1',
        upload_to='teamlead/',
        blank=True
    )
    text2 = models.TextField("Второй абзац")
    image2 = models.ImageField(
        'Картинка 2',
        upload_to='teamlead/',
        blank=True
    )
    text3 = models.TextField("Третий абзац")
    image3 = models.ImageField(
        'Картинка 3',
        upload_to='teamlead/',
        blank=True
    )
    text4 = models.TextField("Четвертый абзац")
    
    
class demandAd(models.Model):
    name = models.TextField('Заголовок')
    
    
class geographyAd(models.Model):
    name = models.TextField('Заголовок')
    
    
class skillsAd(models.Model):
    name = models.TextField('Заголовок')
    
    
class latestAd(models.Model):
    name = models.TextField('Заголовок')
    
    

    

teamlead/views.py
from django.shortcuts import render
from .models import indexPage, demandAd, geographyAd, skillsAd, latestAd

def index(request):
    template = 'index.html'
    pageObj = indexPage.objects.first()
    context = {
        'pageObj': pageObj
    }
    return render(request, template, context)

def demand(request):
    template = 'demand.html'
    pageObj = demandAd.objects.first()
    context = {
        'pageObj': pageObj
    }
    return render(request, template, context)

def geography(request):
    pageObj = geographyAd.objects.first()
    template = 'geography.html'
    context = {
        'pageObj': pageObj
    }
    return render(request, template, context)

def latest_vacancies(request):
    pageObj = latestAd.objects.first()
    template = 'latest_vacancies.html'
    context = {
        'pageObj': pageObj
    }
    return render(request, template, context)

def skills(request):
    pageObj = skillsAd.objects.first()
    template = 'skills.html'
    context = {
        'pageObj': pageObj
    }
    return render(request, template, context)

templates/demand.html
{% include 'includes/headerSidebar.html'%}
  <div class="container" style='padding-bottom: 1000px'>
    <h1 style="padding-top: 25px">{{pageObj.name}}</h1>
  </div>
</div>
{% include 'includes/footer.html'%}

templates/geography.html
{% include 'includes/headerSidebar.html'%}
  <div class="container" style='padding-bottom: 1000px'>
    <h1 style="padding-top: 25px">{{pageObj.name}}</h1>
  </div>
</div>
{% include 'includes/footer.html'%}

templates/includes/footer.html
<footer class=" text-center py-3 bg-dark">
    <p class ="text-white-50">Слукин Михаил Сергеевич РИ-210910</p>
</footer> 

templates/includes/headerSidebar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Главная страница</title>
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'teamlead:index'%}">
          <img src="{% static 'img/logo.jpeg'%}" width="70" height="70" alt="">
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <h2 style="color: white">Руководитель IT проектов</h2>
            </li>
  
        </div>
      </div>
    </nav>
  </header>
  <div style="display: flex">
    <div class="bg-dark">
      <sidebar>
        <nav class="sidebar-sticky navbar-expand-md navbar-dark bg-dark text-center">

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto flex-column">
              <li class="nav-item active">
                <a href="{% url 'teamlead:index'%}" class="nav-link">Главная страница</a>
                <hr style="color:white">
              </li>
              <li class="nav-item">
                <a href="{% url 'teamlead:demand'%}" class="nav-link">Востребованность</a>
                <hr style="color:white">
              </li>
              <li class="nav-item">
                <a href="{% url 'teamlead:geography'%}" class="nav-link">География</a>
                <hr style="color:white">
              </li>
              <li class="nav-item">
                <a href="{% url 'teamlead:skills'%}" class="nav-link">Навыки</a>
                <hr style="color:white">
              </li>
              <li class="nav-item">
                <a href="{% url 'teamlead:latest_vacancies'%}" class="nav-link">Последние вакансии</a>
              </li>
            </ul>
          </div>
        </nav>
      </sidebar>
    </div>

templates/index.html
  {% include 'includes/headerSidebar.html'%}
    <main>
      <div class="container">
        <h1 style="padding-top: 25px; padding-bottom: 10px">Главная страница</h1>
        <p style="padding-bottom: 50px">
          {{pageObj.text1}}
        </p>
      </div>
      <img src="{{pageObj.image1.url}}" class="d-block w-100" alt="...">
      <div class="container" style="padding-top: 100px; padding-bottom: 100px">
        <p>
          {{pageObj.text2}}
        </p>
      </div>
      <img src="{{pageObj.image2.url}}" class="d-block w-100" alt="...">
      <div class="container" style="padding-top: 100px; padding-bottom: 100px">
        <p>
          {{pageObj.text3}}
        </p>
      </div>
      <img src="{{pageObj.image3.url}}" class="d-block w-100" alt="...">
      <div class="container" style="padding-top: 100px; padding-bottom: 100px">
        <p>
          {{pageObj.text4}}
        </p>
      </div>

    </main>
  </div>
    {% include 'includes/footer.html'%}
</body>
</html>

templates/latest_vacancies.html
{% include 'includes/headerSidebar.html'%}
  <div class="container" style="padding-bottom: 1000px">
    <h1 style="padding-top: 25px; padding-bottom: 10px">{{pageObj.name}}</h1>
    
  </div>
</div>
{% include 'includes/footer.html'%}

templates/skills.html
{% include 'includes/headerSidebar.html'%}
  <div class="container" style='padding-bottom: 1000px'>
    <h1 style="padding-top: 25px">{{pageObj.name}}</h1>
    
  </div>
</div>
{% include 'includes/footer.html'%}